baseURL: https://blog.aurora-team.ru/
languageCode: ru-ru
title: Aurora Team Blog
theme: PaperMod

defaultContentLanguage: ru
enableRobotsTXT: true

params:
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  author: JCat
  comments: true
  env: production
  DateFormat: 2 January 2006
  description: Блог о всяком разном
  label:
    icon: /favicon-32x32.png

menu:
  main:
    - identifier: aurora
      name: На основной сайт
      url: https://aurora-team.ru
      weight: 10

imaging:
  quality: 100
